spring:
  application:
    name: Jpa Demo
  datasource:
    url: jdbc:p6spy:mysql://localhost:3307/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: usbw
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: false
#    hibernate:
#      ddl-auto: create
server:
  port: 8080
logging:
  level:
    ROOT: error
    com.example.demo.DemoApplication: info